### ISSUE TITLE
Unable to use "match" as variable name

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog-plugin-pipeline-processor#172]
### Problem description

The rules language doesn't seem to allow `match` as a valid variable name.

### Steps to reproduce the problem

1. Create the following rule:
```
rule "match-test"
when
  true
then
  let match = "test";
end
```
2. Try to save the rule.
3. Witness the following exception:
```
java.lang.NullPointerException
	at org.graylog.plugins.pipelineprocessor.parser.PipelineRuleParser$RuleAstBuilder.exitVarAssignStmt(PipelineRuleParser.java:320)
	at org.graylog.plugins.pipelineprocessor.parser.RuleLangParser$VarAssignStmtContext.exitRule(RuleLangParser.java:1334)
```

### Environment

* Graylog Version: 2.2.x
* Pipeline Processor plugin version: 2.2.x

**Comment by kroepke** [comment]
The underlying issue is that the rule language shares a grammar with the pipeline definition, where `match` is a reserved word.
The two grammars should be separated because they are really not connected to each other.

**Comment by bernd** [comment]
@kroepke I am going to remove this from the 2.3.0 milestone.
