### ISSUE TITLE
JSON rule-based parsing not working although JSON extractor was fine

### ISSUE THREAD

**Issue by tokred** [Graylog2/graylog-plugin-pipeline-processor#40]
### Problem description
_Short:_ I receive events as nested JSON. I want to replace an existing JSON input extractor with the according pipeline rule. However, the nested JSON structure is not extracted successfully by the rule.

_Details:_ I have a service which sends its events directly as JSON messages to a Logstash shipping instance and then via Kafka to Graylog. Raw messages going into the Graylog input look like this:
```
{"message": "{\"timestamp\":\"2016-06-22T12:12:16.353Z\",\"PRI\":14,\"url\":\"/isauthenticated\",\"method\":\"GET\",\"params\":{},\"permissions\":[\"ASA\",\"PVM-OPERATOR\",\"radius-admin\",\"MONITOR_user\",\"DCN_operator\",\"unrestricted\",\"unrestricted_ext\",\"EXT_DIGI\",\"DCN_readonly\",\"DEVICE-OPERATOR\",\"ReadOnly\"],\"username\":\"foo\"}",
"host": "172.0.0.1","log_env": "test","log_collector": "log-shipper02","log_type": "log-nodejs","log_input_type": "syslog-tcp/1514","log_stream": "dcn","log_collector_timestamp": "2016-06-22T12:12:16.355Z"}
```
You can see that the event text from my service gets escaped and written into the "message" field, accompanied by some additional fields from Logstash.

In order to extract this nested information, a JSON Extractor on the input works fine when applied to the "message" field. The Extractor preview gives me

> **method**
>     GET
> **PRI**
>     14
> **url**
>     /isauthenticated
> **permissions**
>     ASA, PVM-OPERATOR, radius-admin, MONITOR_user, DCN_operator, unrestricted, unrestricted_ext, EXT_DIGI, DCN_readonly, DEVICE-OPERATOR, ReadOnly
> **timestamp**
>     2016-06-22T12:12:16.353Z
> **username**
>     foo

which is perfectly fine.

However, substituting the input extractor by the following pipeline rule does not work at all:
````
rule "Rule: Foo"
when
  true
then
  let x = parse_json(to_string($message.message));
  let new_fields = select_jsonpath(x,
            { username: "$['username']",
              url: "$['url']"
            });
  set_fields(new_fields);
end
````
This code is directly from the example: https://github.com/Graylog2/graylog-plugin-pipeline-processor/blob/master/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/jsonpath.txt

The fields "username" and "url" **are created, but remain empty**.
Graylog log is empty, no exceptions are thrown.

### Steps to reproduce the problem

1. Send JSON messages via Logstash to Graylog.
2. Apply a JSON input extractor on the message field and confirm it extracts values.
3. Replace the input extractor with a pipeline rule (see above) and confirm it does not extract the values.

### Environment

* Graylog Version: 2.0.2
* Pipeline Processor plugin version: 1.0.0-beta.4
* Elasticsearch Version: 2.3.2

**Comment by tokred** [comment]
I do not want to be annoying, but this is a serious bug in JSON processing - any updates on this?

I think the unit tests do not cover this appropriately, because they just check the field existence via hasField() and not if content has been extracted.

**Comment by tokred** [comment]
This https://github.com/Graylog2/graylog2-server/issues/1646 would actually also make a lot of sense for a (working) JSON pipeline rule.

**Comment by kroepke** [comment]
@tokred I'll take a look today

**Comment by kroepke** [comment]
@tokred This works with your example rule and message in beta.2:
![screenshot](https://cloud.githubusercontent.com/assets/52014/17363778/c5bfd73a-597c-11e6-8510-66f08be46d0c.png)

**Comment by tokred** [comment]
Great, I will check as soon as beta.2 is released.

**Comment by tokred** [comment]
Just updated to beta.2 to reproduce your success. Unfortunately, the simulator throws an exception and "Simulation results" stays at "Loading":

![tmp](https://cloud.githubusercontent.com/assets/12331973/17394964/1caf921a-5a2c-11e6-99d0-0d19262f31db.JPG)

The exception is:

```
2016-08-04T10:10:48.876+02:00 ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
org.graylog.plugins.pipelineprocessor.ast.exceptions.FunctionEvaluationException: java.lang.NullPointerException
        at org.graylog.plugins.pipelineprocessor.ast.expressions.FunctionExpression.evaluateUnsafe(FunctionExpression.java:65) ~[?:?]
        at org.graylog.plugins.pipelineprocessor.ast.expressions.BooleanValuedFunctionWrapper.evaluateBool(BooleanValuedFunctionWrapper.java:35) ~[?:?]
        at org.graylog.plugins.pipelineprocessor.processors.PipelineInterpreter.processForResolvedPipelines(PipelineInterpreter.java:320) ~[?:?]
        at org.graylog.plugins.pipelineprocessor.processors.PipelineInterpreter.processForPipelines(PipelineInterpreter.java:281) ~[?:?]
        at org.graylog.plugins.pipelineprocessor.processors.PipelineInterpreter.process(PipelineInterpreter.java:238) ~[?:?]
        at org.graylog.plugins.pipelineprocessor.rest.SimulatorResource.simulate(SimulatorResource.java:76) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[graylog.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog.jar:?]
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog.jar:?]
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog.jar:?]
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog.jar:?]
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
        at org.graylog.plugins.pipelineprocessor.functions.FromInput.evaluate(FromInput.java:75) ~[?:?]
        at org.graylog.plugins.pipelineprocessor.functions.FromInput.evaluate(FromInput.java:33) ~[?:?]
        at org.graylog.plugins.pipelineprocessor.ast.expressions.FunctionExpression.evaluateUnsafe(FunctionExpression.java:59) ~[?:?]
        ... 32 more
```

I used the following raw message with GELF message codec and the already mentioned rule:

`{"message":"{\"message_timestamp\":\"2016-08-04T08:09:40.546Z\",\"syslog_pri\":14,\"path\":\"/isauthenticated\",\"environment\":\"prod\",\"method\":\"GET\",\"params\":{}}\n","log_env":"test","log_collector":"log-shipper02","log_type":"log-nodejs","log_input_type":"syslog-udp/1514","log_stream":"dcn","host":"172.25.235.226","log_collector_timestamp":"2016-08-04T08:09:40.550Z"}`

**Comment by kroepke** [comment]
Damn, https://github.com/Graylog2/graylog-plugin-pipeline-processor/pull/72 was merged. Sorry!

**Comment by tokred** [comment]
Not sure if that's the reason for the abovementioned situation. Simulator throws an exception for other messages with GELF too, e.g.

`{"message":"<133>Aug 04 2016 10:48:53: %ASA-5-713120: Group = 172.25.26.76, IP = 172.25.26.76, PHASE 2 COMPLETED (msgid=6ba8ab16)\n","log_env":"test","log_collector":"log-shipper01","log_type":"log-cisco-asa","log_input_type":"syslog-udp/1514","log_stream":"testlab","host":"172.24.150.124","message_timestamp":"2016-08-04T08:48:53.000Z","log_collector_timestamp":"2016-08-04T08:48:53.842Z"}`

Guess that is another issue?

**Comment by kroepke** [comment]
@tokred could it be that the input is no longer there or not running?

**Comment by tokred** [comment]
I checked each from_input. They all refer to valid and existing input ID strings.

Idea: Maybe the reason for the NullPointerException is that a simulated message itself does not contain an input? Therefore the comparison of from_input fails as there is not comparable value?

Have a look at https://github.com/Graylog2/graylog-plugin-pipeline-processor/blob/master/src/main/java/org/graylog/plugins/pipelineprocessor/functions/FromInput.java#L58-L59
Is it possible that for simulated messages the `messageInput.getTitle().equalsIgnoreCase(name)` fails because `messageInput` is maybe null?

Regards

**Comment by tokred** [comment]
I checked each from_input. They all refer to valid and existing input ID strings. However, I had an idea, see https://github.com/Graylog2/graylog2-server/issues/2610

**Comment by kroepke** [comment]
@tokred please have a look at beta.3 to see if that solves your problem. Thank you!

**Comment by tokred** [comment]
@kroepke It works, you guys are awesome! :+1: 
Both issues are resolved in beta.3

**Comment by pratham2003** [comment]
Does this mean that the incoming JSON message is parsed twice?
Once in the pipeline and then again in the message extractor?
