### ISSUE TITLE
The regex() function does not properly parse matcher string to work

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog-plugin-pipeline-processor#45]
### Problem description

When trying to add the following rule, the editor gives me all kinds of syntax errors until I randomly remove brackets and backslashes in it.

```
rule "Extract Snort alert fields"
when
  has_field("message")
then
  let m = regex("^\s?\[(.+?)\] (.+?) \[Classification: (.+?)\] \[Priority: (\d+)] \{(.+?)\} (\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}):(\d{1,5}) -> (\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}):(\d{1,5})", to_string($message.message));
  add_field("first_stuff", m.groups("0"));
end
```

I am also seeing this exception the `graylog-server` log:

```
2016-07-18 00:19:42,644 ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
java.lang.NullPointerException
	at org.graylog.plugins.pipelineprocessor.ast.functions.FunctionArgs.lambda$getConstantArgs$0(FunctionArgs.java:54) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_91]
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1683) ~[?:1.8.0_91]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_91]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_91]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_91]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_91]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_91]
	at org.graylog.plugins.pipelineprocessor.ast.functions.FunctionArgs.getConstantArgs(FunctionArgs.java:55) ~[?:?]
	at org.graylog.plugins.pipelineprocessor.ast.functions.Function.preprocessArgs(Function.java:48) ~[?:?]
	at org.graylog.plugins.pipelineprocessor.ast.expressions.FunctionExpression.<init>(FunctionExpression.java:40) ~[?:?]
	at org.graylog.plugins.pipelineprocessor.parser.PipelineRuleParser$RuleAstBuilder.exitFunctionCall(PipelineRuleParser.java:356) ~[?:?]
	at org.graylog.plugins.pipelineprocessor.parser.RuleLangParser$FunctionCallContext.exitRule(RuleLangParser.java:1323) ~[?:?]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:71) ~[?:?]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:54) ~[?:?]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[?:?]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[?:?]
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52) ~[?:?]
	at org.graylog.plugins.pipelineprocessor.parser.PipelineRuleParser.parseRule(PipelineRuleParser.java:131) ~[?:?]
	at org.graylog.plugins.pipelineprocessor.rest.RuleResource.parse(RuleResource.java:109) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor282.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[graylog2-server-2.1.0-alpha.3-SNAPSHOT-shaded.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[graylog2-server-2.1.0-alpha.3-SNAPSHOT-shaded.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[graylog2-server-2.1.0-alpha.3-SNAPSHOT-shaded.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[graylog2-server-2.1.0-alpha.3-SNAPSHOT-shaded.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[graylog2-server-2.1.0-alpha.3-SNAPSHOT-shaded.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[graylog2-server-2.1.0-alpha.3-SNAPSHOT-shaded.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[graylog2-server-2.1.0-alpha.3-SNAPSHOT-shaded.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[graylog2-server-2.1.0-alpha.3-SNAPSHOT-shaded.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) [graylog2-server-2.1.0-alpha.3-SNAPSHOT-shaded.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [graylog2-server-2.1.0-alpha.3-SNAPSHOT-shaded.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [graylog2-server-2.1.0-alpha.3-SNAPSHOT-shaded.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [graylog2-server-2.1.0-alpha.3-SNAPSHOT-shaded.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [graylog2-server-2.1.0-alpha.3-SNAPSHOT-shaded.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [graylog2-server-2.1.0-alpha.3-SNAPSHOT-shaded.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [graylog2-server-2.1.0-alpha.3-SNAPSHOT-shaded.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) [graylog2-server-2.1.0-alpha.3-SNAPSHOT-shaded.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) [graylog2-server-2.1.0-alpha.3-SNAPSHOT-shaded.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:384) [graylog2-server-2.1.0-alpha.3-SNAPSHOT-shaded.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224) [graylog2-server-2.1.0-alpha.3-SNAPSHOT-shaded.jar:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176) [graylog2-server-2.1.0-alpha.3-SNAPSHOT-shaded.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

### Steps to reproduce the problem

1. Try to create the rule and look at the syntax errors the editor gives you.

### Environment

* Graylog Version: 2.1.0-alpha.3
* Pipeline Processor plugin version: 1.1.0-alpha.2 (built from current `master`)
* Elasticsearch Version: 2.3.1
* MongoDB Version: 3.0.0
* Operating System: OSX

**Comment by edmundoa** [comment]
The issue with your input is that you are not giving a valid Java String literal. Backslashes must be escaped, so the regex should look like:

`"^\\s?\\[(.+?)\\] (.+?) \\[Classification: (.+?)\\] \\[Priority: (\\d+)] \\{(.+?)\\} (\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}):(\\d{1,5}) -> (\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}):(\\d{1,5})"`

Unfortunately that will not work when matching the regular expression against the stream, as the escape characters are not removed from the string afterwards. I'm currently working on a fix for that.

**Comment by edmundoa** [comment]
Testing the changes I did for #46, the only problems I found with the rule you posted are actual syntax errors. This is how the rule should look like:

```
rule "Extract Snort alert fields"
when
  has_field("message")
then
  let m = regex("^\\s?\\[(.+?)\\] (.+?) \\[Classification: (.+?)\\] \\[Priority: (\\d+)] \\{(.+?)\\} (\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}):(\\d{1,5}) -> (\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}):(\\d{1,5})", to_string($message.message));
  set_field("first_stuff", m["0"]);
end
```

I'm closing the issue now, please reopen if you still have some problems with it.

**Comment by lennartkoopmann** [comment]
Thank you @edmundoa! :) @jalogisch Can you make sure that this is reflected in the documentation of the `regex` pipeline processor function? I really struggled with this.

**Comment by edmundoa** [comment]
@lennartkoopmann Welcome!

I have created Graylog2/documentation#131 so we don't forget about it. I also had to look at the tests to know how to use the results of calling the `regex` function.

**Comment by lennartkoopmann** [comment]
I just tried it out and it unfortunately does not work:

```
2016-07-19 13:53:08,994 ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
java.util.regex.PatternSyntaxException: Illegal repetition near index 73
^\\s?\\[(.+?)\\] (.+?) \\[Classification: (.+?)\\] \\[Priority: (\\d+)] \\{(.+?)\\} (\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}):(\\d{1,5}) -> (\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}):(\\d{1,5})
```

It looks like the backslash is escaping the backslash and the curly bracket (repitition) is left unescaped.

Could it be that the `java.util.regex.Pattern` does not require the double escaping but only the rule validation logic (that keeps you from saving the rule) does?

**Comment by edmundoa** [comment]
Hmm, I wonder why it was working for me yesterday. When do you see that error? When trying to save the rule?

Did you try creating the rule against #47? Maybe it helps, as the backslash escaping was broken before that.

**Comment by lennartkoopmann** [comment]
Thanks! Will try against #47 later today.

I am seeing the error in the `graylog-server` log file when trying to save.

**Comment by lennartkoopmann** [comment]
@edmundoa #47 does indeed fix the issue for me! Thanks!
