### ISSUE TITLE
String conversion problem with select_jsonpath() function

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog-plugin-pipeline-processor#68]
### Problem description

When trying to use the `select_jsonpath()` function, storing a message with an extracted String in Elasticsearch will fail:

```
2016-07-29T15:51:33.188-05:00 ERROR [BlockingBatchedESOutput] Unable to flush message buffer
java.lang.ClassCastException: Cannot cast com.fasterxml.jackson.databind.node.TextNode to java.lang.String
	at java.lang.Class.cast(Class.java:3369) ~[?:1.8.0_101]
	at org.graylog2.plugin.Message.getFieldAs(Message.java:371) ~[graylog.jar:?]
	at org.graylog2.plugin.Message.getMessage(Message.java:287) ~[graylog.jar:?]
	at org.graylog2.plugin.Message.toElasticSearchObject(Message.java:216) ~[graylog.jar:?]
	at org.graylog2.indexer.messages.Messages.bulkIndex(Messages.java:116) ~[graylog.jar:?]
	at org.graylog2.indexer.messages.Messages.bulkIndex(Messages.java:106) ~[graylog.jar:?]
	at org.graylog2.outputs.ElasticSearchOutput.write(ElasticSearchOutput.java:98) ~[graylog.jar:?]
	at org.graylog2.outputs.BlockingBatchedESOutput.flush(BlockingBatchedESOutput.java:128) [graylog.jar:?]
	at org.graylog2.outputs.BlockingBatchedESOutput.forceFlushIfTimedout(BlockingBatchedESOutput.java:158) [graylog.jar:?]
	at org.graylog2.periodical.BatchedElasticSearchOutputFlushThread.doRun(BatchedElasticSearchOutputFlushThread.java:88) [graylog.jar:?]
	at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
````

Calling `to_string()` on the extracted field works, but will wrap the string in quotes. I had to use another `regex()` function to get rid of the quotes.

### Environment

* Graylog Version: 2.1.0-beta.1
* Pipeline Processor plugin version: 1.1.0-beta.1
* Elasticsearch Version: 2.3.1

**Comment by tokred** [comment]
May I ask which rule code you used? Because for me, select_jsonpath is not working at all, however lacks an exception, see https://github.com/Graylog2/graylog-plugin-pipeline-processor/issues/40
